title:               Gamekeller League of Legends Turniere
description:         Die neusten Informationen über die offiziellen Gamekeller League of Legends Turniere.
url:                 http://lol.gamekeller.net
permalink:           pretty
paginate:            5
paginate_path:       /page/:num/

gems:
  - jekyll-paginate
  - jemoji
