# Setup
title:               Gamekeller League of Legends Turniere
description:         Die neusten Informationen über die offiziellen Gamekeller League of Legends Turniere.
url:                 http://lol.gamekeller.net
paginate:            5
permalink:           pretty

gems:
  - jekyll-paginate
  - jemoji
